name: Label Old PRs

on:
  # schedule:
  #   - cron: '0 15 * * *'
  workflow_dispatch: # 手動実行のオプション

permissions:
  contents: read
  pull-requests: write

jobs:
  label-old-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install octokit moment-business-days

      - name: Run labeling script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: node scripts/labelOldPRs.mjs

